# permissions for end users to view demoservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoservice-viewer-role
rules:
- apiGroups:
  - app.zyx.io
  resources:
  - demoservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.zyx.io
  resources:
  - demoservices/status
  verbs:
  - get
